<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="GTI" time="641.872" tests="2" failures="0" errors="1">
   <testsuite name="GTI" tests="2" failures="0" errors="1" time="641.872" skipped="0" timestamp="2023-09-15 18:00:49" hostname="SEU2K19KAT01$ - seu2k19kat01.redseur.local" id="Test Suites/GTI">
      <properties>
         <property name="deviceName" value=""/>
      </properties>
      <testcase name="Test Cases/Host/01 - HostRun - Seur8as" time="53.299" classname="Test Cases/Host/01 - HostRun - Seur8as" status="PASSED">
         <system-out><![CDATA[2023-09-15 18:01:59 - [TEST_CASE][PASSED] - Test Cases/Host/01 - HostRun - Seur8as: Test Cases/Host/01 - HostRun - Seur8as
2023-09-15 18:01:59 - [TEST_STEP][PASSED] - operativaHost = <not implemented yet for class: org.codehaus.groovy.ast.expr.EmptyExpression>: null]]></system-out>
         <system-err><![CDATA[]]></system-err>
      </testcase>
      <testcase name="Test Cases/Host/01 - HostRun" time="160.978" classname="Test Cases/Host/01 - HostRun" status="ERROR">
         <error type="ERROR" message="Test Cases/Host/01 - HostRun FAILED.
			Reason:
			com.kms.katalon.core.exception.StepErrorException: Se ha producido un error, durante el proceso del host, en la fila: 9
				at com.kms.katalon.core.util.KeywordUtil.markErrorAndStop(KeywordUtil.java:74)
				at com.kms.katalon.core.util.KeywordUtil$markErrorAndStop$1.call(Unknown Source)
				at toolsHost.LogUtils.loggerBusinessError(LogUtils.groovy:221)
				at 01 - HostRun.run(01 - HostRun:58)
				at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
				at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
				at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:430)
				at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:421)
				at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:400)
				at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:392)
				at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:273)
				at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:202)
				at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:164)
				at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:105)
				at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:185)
				at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
				at TempTestSuite1699255247527.run(TempTestSuite1699255247527.groovy:36)
			"/>
					<system-out><![CDATA[2023-11-06 08:20:51 - [TEST_CASE][ERROR] - Test Cases/Host/01 - HostRun: Test Cases/Host/01 - HostRun FAILED.
			Reason:
			com.kms.katalon.core.exception.StepErrorException: Se ha producido un error, durante el proceso del host, en la fila: 9
				at com.kms.katalon.core.util.KeywordUtil.markErrorAndStop(KeywordUtil.java:74)
				at com.kms.katalon.core.util.KeywordUtil$markErrorAndStop$1.call(Unknown Source)
				at toolsHost.LogUtils.loggerBusinessError(LogUtils.groovy:221)
				at 01 - HostRun.run(01 - HostRun:58)
				at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
				at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
				at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:430)
				at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:421)
				at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:400)
				at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:392)
				at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:273)
				at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:202)
				at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:164)
				at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:105)
				at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:185)
				at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
				at TempTestSuite1699255247527.run(TempTestSuite1699255247527.groovy:36)]]></system-out>
      <system-err><![CDATA[]]></system-err>
   </testsuite>
</testsuites>